In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Feature Engineering

In [2]:
dff = pd.read_csv("data_reg.csv")

In [3]:
dff

,Unnamed: 0,date,id,activity,circumplex.arousal,circumplex.valence,mood,appCat.builtin,appCat.communication,appCat.entertainment,...,day_2,day_3,day_4,day_5,day_6,month_2,month_3,month_4,month_5,month_6
0,0,2014-02-26,AS14.01,0.090464,-0.250000,0.75,6.25,0.000,0.000,0.000,...,1,0,0,0,0,1,0,0,0,0
1,1,2014-03-21,AS14.01,0.134050,0.200000,0.20,6.20,1090.617,2850.042,100.898,...,0,0,1,0,0,0,1,0,0,0
2,2,2014-03-22,AS14.01,0.236880,0.600000,0.50,6.40,476.737,1946.683,4.010,...,0,0,0,1,0,0,1,0,0,0
3,3,2014-03-23,AS14.01,0.142741,0.200000,0.80,6.80,540.915,2680.535,4.028,...,0,0,0,0,1,0,1,0,0,0
4,4,2014-03-24,AS14.01,0.078961,0.800000,0.00,6.00,731.456,5070.628,70.289,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1207,2014-05-26,AS14.33,0.115201,-0.400000,0.00,5.40,571.902,750.571,79.963,...,0,0,0,0,0,0,0,0,1,0
1208,1208,2014-05-27,AS14.33,0.012704,-0.600000,0.40,6.20,269.550,771.182,32.137,...,0,0,0,0,0,0,0,0,1,0
1209,1209,2014-05-28,AS14.33,0.103301,0.000000,1.20,8.20,1093.741,1057.568,153.121,...,1,0,0,0,0,0,0,0,1,0
1210,1210,2014-05-29,AS14.33,0.169354,-1.333333,1.00,7.00,248.063,198.112,5.018,...,0,1,0,0,0,0,0,0,1,0
1211,1211,2014-05-30,AS14.33,0.192901,-0.800000,-0.40,6.80,930.885,992.321,21.178,...,0,0,1,0,0,0,0,0,1,0

In [4]:
dff = dff.drop(['id','date','Unnamed: 0'], axis = 1)

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

# Assuming 'dff' is your DataFrame and has been properly loaded and prepared
X = dff.drop([ 'mood'], axis=1)
y = dff['mood']

# Initialize the scaler
scaler = MinMaxScaler()

# Scale the features (X)
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)  # Convert the scaled array back to a DataFrame

# Combine the scaled features with the target variable into a new DataFrame
df_scaled = pd.concat([X_scaled, y.reset_index(drop=True)], axis=1)

In [6]:
#dff.to_csv('outtt.csv') 
dff

,activity,circumplex.arousal,circumplex.valence,mood,appCat.builtin,appCat.communication,appCat.entertainment,appCat.finance,appCat.game,appCat.office,...,day_2,day_3,day_4,day_5,day_6,month_2,month_3,month_4,month_5,month_6
0,0.090464,-0.250000,0.75,6.25,0.000,0.000,0.000,0.000,0.0,0.000,...,1,0,0,0,0,1,0,0,0,0
1,0.134050,0.200000,0.20,6.20,1090.617,2850.042,100.898,49.544,0.0,5.479,...,0,0,1,0,0,0,1,0,0,0
2,0.236880,0.600000,0.50,6.40,476.737,1946.683,4.010,21.076,0.0,0.000,...,0,0,0,1,0,0,1,0,0,0
3,0.142741,0.200000,0.80,6.80,540.915,2680.535,4.028,43.403,0.0,0.000,...,0,0,0,0,1,0,1,0,0,0
4,0.078961,0.800000,0.00,6.00,731.456,5070.628,70.289,34.106,0.0,3.010,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,0.115201,-0.400000,0.00,5.40,571.902,750.571,79.963,0.000,0.0,0.000,...,0,0,0,0,0,0,0,0,1,0
1208,0.012704,-0.600000,0.40,6.20,269.550,771.182,32.137,0.000,0.0,0.000,...,0,0,0,0,0,0,0,0,1,0
1209,0.103301,0.000000,1.20,8.20,1093.741,1057.568,153.121,0.000,0.0,38.262,...,1,0,0,0,0,0,0,0,1,0
1210,0.169354,-1.333333,1.00,7.00,248.063,198.112,5.018,0.000,0.0,0.000,...,0,1,0,0,0,0,0,0,1,0
1211,0.192901,-0.800000,-0.40,6.80,930.885,992.321,21.178,0.000,0.0,0.000,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import RFECV
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from sklearn.model_selection import TimeSeriesSplit

# Assuming 'dff' is your DataFrame and 'X_scaled' and 'y' have been prepared for a regression task
# Initialize the regressor with 50 estimators
regressor = RandomForestRegressor(n_estimators=10, random_state=42)

tscv = TimeSeriesSplit(n_splits=5)

# Create the RFE object with cross-validation for regression
rfecv = RFECV(estimator=regressor, step=2, cv=tscv, scoring='neg_mean_squared_error')

# Fit RFECV to the scaled features and the target
rfecv.fit(X_scaled, y)

# List the best features: features with support_ = True are selected
selected_features = [X_scaled.columns[i] for i in range(X_scaled.shape[1]) if rfecv.support_[i]]

# Print the selected features
print("Selected features:", selected_features)

In [ ]:
X_r = X_scaled[selected_features]

# MSE

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV, TimeSeriesSplit, cross_val_score
from sklearn.metrics import mean_squared_error, classification_report, confusion_matrix, precision_score, recall_score, auc, roc_curve, accuracy_score, f1_score, roc_auc_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.linear_model import Ridge, RidgeCV, ElasticNet, LassoCV, LassoLarsCV, LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier


# Assuming X_bs and y have been defined and preprocessed properly for regression

# Initialize TimeSeriesSplit
#tscv = TimeSeriesSplit(n_splits=5)

# Determine the train and test indices from the last split
train_index, test_index = next(reversed(list(tscv.split(X_r))))
X_train, X_test = X_r.iloc[train_index], X_r.iloc[test_index]
y_train, y_test = y.iloc[train_index], y.iloc[test_index]

grid_models = [
    (LinearRegression(), [{}]), 
    (Ridge(), [{'alpha': np.logspace(-6, 1, 100), 'random_state': [0]}]),
    (Lasso(), [{'alpha': np.logspace(-6, 1, 100), 'random_state': [0]}]),
    (DecisionTreeRegressor(), [{'criterion': ['squared_error', 'friedman_mse', 'absolute_error'], 'random_state': [0]}]),
    (RandomForestRegressor(), [{'n_estimators': [100, 150, 200], 'criterion': ['squared_error', 'absolute_error'], 'random_state': [0]}]),
    (AdaBoostRegressor(), [{'n_estimators': [100, 150, 200], 'learning_rate': [0.1, 0.5, 0.8, 1], 'loss': ['linear', 'square', 'exponential'], 'random_state': [0]}]),
    (GradientBoostingRegressor(), [{'n_estimators': [100, 150, 200], 'criterion': ['friedman_mse', 'squared_error'], 'loss': ['squared_error', 'absolute_error', 'huber'], 'learning_rate': [0.1, 0.5, 0.8, 1], 'random_state': [0]}]),
    (XGBRegressor(), [{'learning_rate': [0.01, 0.05, 0.1], 'n_estimators': [100, 150, 200], 'random_state': [0], 'eval_metric': ['rmse', 'mae']}])
]

model_results = []

# Perform Grid Search for each model and test them
for model_name, (model, params) in models_params.items():
    grid = GridSearchCV(estimator=model, param_grid=params, scoring='neg_mean_squared_error', cv=tscv, n_jobs=-1, verbose=1)
    grid.fit(X_train, y_train)
    best_params = grid.best_params_
    best_score = -grid.best_score_  # Take the negative of the score because 'neg_mean_squared_error' is negative
    
    # Train the best model from GridSearchCV
    best_model = grid.best_estimator_
    best_model.fit(X_train, y_train)
    
    # Make predictions on the test set
    y_pred = best_model.predict(X_test)
    
    # Evaluate the model performance on the test set using MSE and R2 score
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    print(f'{model_name}: MSE = {mse:.2f}, R2 = {r2:.2f}')
    
    model_results.append({
        'Model': model_name,
        'Best Score (Neg MSE)': f'{best_score:.2f}',
        'Test MSE': f'{mse:.2f}',
        'Test R2 Score': f'{r2:.2f}',
        'Best Parameters': best_params
    })

# Convert results to DataFrame for better visualization
results_df_mse = pd.DataFrame(model_results)
print(results_df)

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, explained_variance_score

def evaluation(X_train, X_test,y_train, y_test, best_model):
    best_model.fit(X_train,y_train)
    y_pred = best_model.predict(X_test)
# Calculate MSE
    mse = mean_squared_error(y_test, y_pred)

    # Calculate RMSE
    rmse = mse ** 0.5

    # Calculate MAE
    mae = mean_absolute_error(y_test, y_pred)

    # Calculate R-squared
    r2 = r2_score(y_test, y_pred)

    # Calculate Explained Variance Score
    explained_variance = explained_variance_score(y_test, y_pred)


    # Print the results
    print("Mean Squared Error (MSE):", mse)
    print("Root Mean Squared Error (RMSE):", rmse)
    print("Mean Absolute Error (MAE):", mae)
    print("R-squared (Coefficient of Determination):", r2)
    print("Explained Variance Score:", explained_variance)

evaluation(X_train, X_test, y_train, y_test, best_model)

In [ ]:
results_df_mse.to_csv('mse_results.csv', index=False)

# MAE

In [ ]:

# Assuming X_bs and y have been defined and preprocessed properly for regression

# Initialize TimeSeriesSplit
#tscv = TimeSeriesSplit(n_splits=5)


model_results = []

# Perform Grid Search for each model and test them
for model_name, (model, params) in models_params.items():
    grid = GridSearchCV(estimator=model, param_grid=params, scoring='neg_mean_absolute_error', cv=tscv, n_jobs=-1, verbose=1)
    grid.fit(X_train, y_train)
    best_params = grid.best_params_
    best_score = -grid.best_score_  # Take the negative of the score because 'neg_mean_squared_error' is negative
    
    # Train the best model from GridSearchCV
    best_model = grid.best_estimator_
    best_model.fit(X_train, y_train)
    
    # Make predictions on the test set
    y_pred = best_model.predict(X_test)
    
    # Evaluate the model performance on the test set using MSE and R2 score
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    print(f'{model_name}: MSE = {mse:.2f}, R2 = {r2:.2f}')
    
    model_results.append({
        'Model': model_name,
        'Best Score (Neg MSE)': f'{best_score:.2f}',
        'Test MSE': f'{mse:.2f}',
        'Test R2 Score': f'{r2:.2f}',
        'Best Parameters': best_params
    })

# Convert results to DataFrame for better visualization
results_df_mae = pd.DataFrame(model_results)
print(results_df)

In [ ]:
evaluation(X_train, X_test, y_train, y_test, best_model)

In [ ]:
results_df_mae.to_csv('mae_results.csv', index=False)